Tipografy  + Getting started page
placetopay-org/spartan-docs pull request #3
Opened 2020-11-26 22:05 UTC by alexhenaof

Typography page and Getting started page

2020-12-07 14:37 UTC, eduarguz requested changes

2020-12-07 14:37 UTC, eduarguz commented on source/docs/styles/color-system.blade.md
> +<div class="flex flex-wrap -mx-2 overflow-hidden">
Estas paletas secundarias deben incluir todos los colores que estamos usando

Por ejemplo, para las alertas estamos usando `green-50` `green-400` `green-800` `green-500` `green-100`

Por ese lado son 5 verdes, y acá solo se están listando 2

2020-12-07 14:37 UTC, eduarguz commented on source/docs/styles/typography.blade.md
> +## Headings {#headings}
Estos ejemplos no deben ir con Iframes? y el código que necesito para usarlos?

2020-12-07 14:37 UTC, eduarguz commented on source/docs/components/modals.blade.md
> +        <div class="m-auto w-3/5 block p-4 bg-white rounded-md shadow relative">
Este componente debe ir en un iframe, la idea es que esté aislado del contenido que lo rodea

Otra ventaja de dejarlo en un iframe, es que podemos agregar una funcionalidad para que se haga responsive. 

Además se mantiene consistente con lo que estamos haciendo en otras páginas (buttons, alerts etc)

2020-12-07 14:37 UTC, eduarguz commented on source/docs/components/authentication.blade.md
> +@component('_partials.iframe', ["height" => "600px;"])
este componente aparece con unos espacios en blanco, recuerda que la intención del iframe es que funcione como una pantalla, y al tamaño de una pantalla.

En este caso, esos espacios en blaco van así?
![image](https://user-images.githubusercontent.com/14934055/101362175-c30e0a00-386d-11eb-9251-1250c0c44c05.png)

2020-12-07 14:37 UTC, eduarguz commented on source/docs/components/authentication.blade.md
> +@component('_partials.iframe', ["height" => "600px;"])
Así se ve la implementación que hicimos para Accounts. 
![image](https://user-images.githubusercontent.com/14934055/101362345-ffda0100-386d-11eb-8e58-7aefef92d6aa.png)

Así se ve la propuesta aquí

![image](https://user-images.githubusercontent.com/14934055/101362440-1aac7580-386e-11eb-8f05-5fc3405dec33.png)


Hay algunas diferencias

2020-12-07 14:37 UTC, eduarguz commented on source/docs/components/alerts.blade.md
> +### Success {#alerts-notifications-success}
Esta no es la alerta con la que habíamos quedado, o al menos se ve un poco rara


![image](https://user-images.githubusercontent.com/14934055/101363158-0b79f780-386f-11eb-8520-a05934a848d1.png)

2020-12-07 14:37 UTC, eduarguz commented on source/docs/components/alerts.blade.md
> +<div class="bg-green-50 border-l-4 border-green-400 p-4">
Iframe

2020-12-07 14:37 UTC, eduarguz commented on source/docs/components/placeholders.blade.md
> +<div class="flex flex-col sm:flex-row md:flex-row lg:flex-row justify-between content-start mb-5">
Iframe

2020-12-07 14:37 UTC, eduarguz commented on source/docs/components/containers.blade.md
> +## Corner radius
Iframes

2020-12-11 20:07 UTC, alexhenaof commented on source/docs/components/alerts.blade.md
> +### Success {#alerts-notifications-success}
Me puedes enviar una captura de la que tienes implementada porfavor. Gracias

2020-12-23 20:53 UTC, merged